### ISSUE TITLE
[MVS optimization&improvement] - JSON library

### ISSUE THREAD

**Issue by betachen** [mvs-org/metaverse#189]
我们发现boost库中JSON解析有两大问题：

### 1.  Boost库的JSON 输出不符合JSON标准
JSON的输出全部以字符串的形式表示，这不符合JSON 对象的标准，同时我们在Boost的提案中也发现了此问题：https://svn.boost.org/trac10/ticket/9721
在当前最新版本(v1.6.5) 依然存在。

所以我们考虑两种选择，
**A** 将boost库中的ptree 实现转变为 MVS 中的私有实现，并增加 数值化的支持；
可以[参考这里的实现](https://stackoverflow.com/questions/2855741/why-boost-property-tree-write-json-saves-everything-as-string-is-it-possible-to)

**B** 考虑集成一个新的json解析库 [jsoncpp](https://github.com/open-source-parsers/jsoncpp);

### 2.  Boost库的JSONj解析速度不是令人满意；
推荐以上方案B解决问题2；

方案A，工作量小，但是不确定是否有衍生问题，因为我们并不知道boost库不集成修改的理由是什么。
方案B，工作量大，需要评估时间。

我推荐方案B；

**Comment by sikamedia** [comment]
Lets discuss in English. 

1. "Boost confirms its implementation has no 100% conformance to JSON standard"  
2. The long term goal for MVS is to have service oriented (BaaS) approach. 

It should replace the Boost JSON implementation in MVS step by step.  Make it be compatible for JSONRPC. 

For my understanding, a good JSON Lib should support serialisation and deserialisation of Object. Seems jsoncpp does [(simple-class-serialization-with-jsoncpp)](http://www.danielsoltyka.com/programming/2011/04/15/simple-class-serialization-with-jsoncpp/) .

Question: Does jsoncpp have 100% conformance to JSON standard?

**Comment by sikamedia** [comment]
I have  imported  jsoncpp into MVS, and tried it with fetch-height.  [bring_jsoncpp_library_to_mvs](https://github.com/sikamedia/metaverse/commits/jsoncpp_json_library)
  ./mvs-cli fetch-height returns json formatted data rather than only height number.
{
	"blockHeight" : 760096
}

It would be nice to  to have ideas on where to implement commands for replacing prop_tree.hpp with jsoncpp. I mean how to organize the code.

**Comment by betachen** [comment]
merged on branch develop.
need testing.

**Comment by betachen** [comment]
v0.7.3 released. then closed.
