### ISSUE TITLE
Requires mvsd export key-store-file same format as lightwallet format

### ISSUE THREAD

**Issue by betachen** [mvs-org/metaverse#248]
Requires mvsd export key-store-file same format as lightwallet format.

**Comment by chengzhpchn** [comment]
1. lightwallet use CryptoJS-- an open-source crypto library for javascript to export encrypted mnemonic;
2. During that procedure, the user-sepcified passphrase and a salt(a random uint64_t number) are used as input of MDS digest Alg, to derive the key and iv of AES_256 encrypt Alg(Mode CBC);
3. The last procedure: mix the salt and encrypted cipher_text and encode to Base64.

I have implement the same function in C++, so that the mvsd and the lightwallet can share the same key-store-file.

More details:
1. From now on, the mvsd dumpkeyfile command will export key file in json format, which is compatable with lightwallet;
2. However, lightwallet's key-store-file contains mnemonic only, the full account info is also export by mvsd, which remains the same format with the old mvsd version.
3. Both the key-store file exported by old and new mvsd, can be imported by new mvsd.

**Comment by chengzhpchn** [comment]
this feature has been published with Super Nova
