### ISSUE TITLE
Request: Wallet Detect New Versions/Updates

### ISSUE THREAD

**Issue by CaptainStevey** [mvs-org/metaverse#304]
It may be worth adding a check of some kind for updates to the wallet.  Whether it be used for all updates, or for essential updates i.e  the one below is essential

"We have fixed a bug that may cause database corruption and uploaded a new installation version.
We recommend that you download the new version from https://mvs.org/wallet.html and upgrade before June 18 at 24:00 PM (GMT+8). "

**Comment by jowenshaw** [comment]
thank for your suggestion, we' ll use <https://github.com/mvs-org/metaverse/releases> to release/update wallet, and write the essential informations for each release.
NOTICE, the master branch is in continuously developing. You may depend on the tag instead of master branch to build wallet of specified version.

**Comment by masterkain** [comment]
what's the best way to keep updated an ubuntu metaverse wallet deployed via the official docker image?

**Comment by canguruhh** [comment]
we can let the frontend check for new releases

**Comment by LaurentSalou** [comment]
Already implemented since v0.7.4
On the login page, it shows a warning message if there is a new wallet version, and a error message if the wallet update is mandatory (hard fork)
Both messages are displayed on top of the page
