### ISSUE TITLE
pool thinks it mined block 1472288, what was registered on blockchain: 1472289

### ISSUE THREAD

**Issue by NotoriousPyro** [mvs-org/metaverse#329]
My pool at Metaverse.farm has a weird problem I've not been able to figure out why. This seems to happen a lot more on smaller hashrate pools, obviously because the blocks are already found by the bigger pools so this doesn't appear as much for them - but it does happen.

My pool uses fetchheaderext to fetch the block data for 1472288 and submitted it as work using eth_SubmitWork for v3. This behaviour has also been noted on v1 and v2.

So my client submits work for 1472288 (https://explorer.mvs.org/blk/1472288) and the work is accepted by the blockchain. The pool registers the block as 1472288 as this was the blockTemplate being worked on, but when this block is checked, it shows it was mined by MLRhd5c3gkXsxph7sTnShCdRBzT6QScmzN

If you view block 1472289 (https://explorer.mvs.org/blk/1472289), this the block data my pool actually submitted but the pool thinks it is 1472288.

![image](https://user-images.githubusercontent.com/706132/45028179-e8cb5980-b03b-11e8-936f-4bdff31a6c7b.png)

Originally, I figured this was due to ETP having no uncles. But it seems like uncles are being accepted regardless. I think this presents a problem where someone can submit an orphaned block as a solution, to have it accepted as the _next_ block provided the block is valid and is close enough difficulty, etc. The time difference between blocks is 2 seconds. The block seems to me like an uncle.

Example:
Say I am mining block 1000

Block is simultaneously found by Pool A and Pool B, and both submit the block using ok, err := s.rpc().SubmitWork(params). Both pools have valid work but there's a delay in getting a response from Pool B's block submission, but both are accepted by the network, Pool A's submitted block is accepted as block 1000. Pool B's submitted block is accepted as block 1001 but it thinks it just submitted block 1000(so it thinks) as that is what is in blockTemplate. But it didn't just submit block 1000... It thought it did, but the network inserted it as block 1001...

The problem is that the wallet accepts the block even though it is work for the previous block and thus the wallet thinks it mined block 1000, but it actually mined 1001, using correct but OLD work.

The only way I can see to fix this, is to get the block height from the submitted hash and update this. But the problem remains: **why is the wallet accepting old work as new work?**

I think this is having an unfair effect on mining, as big pools can just keep submitting valid blocks which will be accepted regardless provided it's close **_enough_**. **_In all honesty, I could remove the check for  stale blocks and just submit it anyway I'm sure it would be accepted..._**

**Comment by NotoriousPyro** [comment]
Just to note, if both blocks are accepted, do both blocks contain the same transactions and thus double spending?

**Comment by chengzhpchn** [comment]
hello, each time the getwork(or eth_getwork) api call will return a headerhash of the pending block, which is caculated by the following function: 
./src/lib/consensus/common/libdevcore/BasicType.cpp:121
h256 HeaderAux::hashHead(libbitcoin::chain::header& _bi)
{
    h256 memo;
    RLPStream s;
    s  << (bigint) _bi.version << (bigint)_bi.bits << (bigint)_bi.number << _bi.merkle
        << _bi.previous_block_hash << (bigint) _bi.timestamp ;
    memo = sha3(s.out());
    return memo;
}
Note:
1. number -- means block height is immutable.
2. merkle --means the transactions in block is immutable.
3. previous_block_hash -- means the previous block is immutable.
So, each time the result of submitwork is only suitable to a specific block, which is at a specific height, with specific transactions, following a specific previous block.

However, I'm not sure why is your mining pool mined 1472289 but shown as 1472288, but the other blocks in your mining pool seems all right.

Since we have supply ETP mining pool setup guide, with the source code patch:
https://docs.mvs.org/docs/setup_mining_pool.html

Maybe you can refer to this guide by comparing your source code with it.
Code review suggestions/questions are welcome.

and we are cooperate with a nameless mining pool, this code patch seems work well recently.

**Comment by NotoriousPyro** [comment]
This issue has been present since v1 of the api. This is not something new and no, the patch does not "work" as none of the changes which are different to my pool are anything relevant to submitting a block.

Most of the edits are the same anyway but I've been working at it longer than you guys and in fact, I'd say my pool operates better than the default. 

I know why it happens, because the wallet accepts the block, its accepting old work as the pool was mining the first block, submitted the work but the block chain inserted the number as the block after.

My pool wouldn't submit the block if the wallet didn't return "true"

**Comment by NotoriousPyro** [comment]
I've noticed the behaviour on several pools so this isn't something specific to me.

**Comment by chengzhpchn** [comment]
I find a probable reason:
the mining pool get mvs work by 2-step rpc calls:
1. fetchPendingBlock( -- MVS API: fetchheaderext), which will return the difficulty and block height
2. getwork, which will return headerhash, target( the other expression of difficulty) and seedhash( used in ethash epoch alg )
if  the wallet syncs a new block during the 2 rpc calls, this may lead to your case:
1. the mining pool considers it is mining at the height of 1472288( which is returned by the 1st rpc call);
2. but the wallet knows the actual work is corresponding to 1472289;
3. when the mining pool submit a valid work, the wallet accept it and commit a new block at 1472289, but the mining pool record the submit as 1472288.

do you think this sounds right?

**Comment by NotoriousPyro** [comment]
I know why it happens is because of what you say about 2 RPC calls. The block being saved to the backend is what the problem is but it's only saving due to the wallet returning true.

If both pools request work for block 1000, they're both working on the same block target, whether the subsequent RPC call updates the block height or not I don't think is the problem. I think the problem is why the wallet is accepting both work as the correct work. If you were to getWork before you saved the block and re-verified, the target for the next block should be different and so the block should not validate. Say for example if you were to submitWork, then run getWork and then compare the block being submitted to getWork, it would not validate.

**Comment by chengzhpchn** [comment]
I think you have miss-understand the mining procedure.
Each mining pool get different work even if they are mining at the same block height.
As I have mentioned above, the work contain the headerhash of the pending block, which is composed of: 
s << (bigint) _bi.version << (bigint)_bi.bits << (bigint)_bi.number << _bi.merkle
<< _bi.previous_block_hash << (bigint) _bi.timestamp ;
Since different mining pools have different wallet address, that will lead to different coinbase-transaction-reward-address for the pending block, of cource the other transactions in that block maybe also different(either in content or in order). but the coinbase-address is enough to make the merkle tree of the block different from each other. and the merkle tree is also a part of the headhash of the pending block, this will make the work different from different mining pools.

So, the miners submit nonce is suitable to only one mining pool, they cannot cheat by submit the same nonce to the other mining pools to get more than 1 reward shares. 
Neither can the miners keep the final nonce to produce the pending block to reward himself, because his pending block does not match the nonce.

and the same nonce does not match different blocks either, since the block height and previous block hash is included in the pending block's headhash

**Comment by NotoriousPyro** [comment]
> I think you have miss-understand the mining procedure.

I think you are right.
